
#define MAX_LINE_LENGTH 80
#define  MAX_FILE_NAME_LENGTH 100 /*todo:ask*/

#define SOURCE_ADDRESSING_POSITION 9
#define OP_CODE_POSITION 5
#define TARGET_ADDRESSING_POSITION 2
#define ARE_POSITION 0

#define SOURCE_REGISTER_POSITION 7
#define TARGET_REGISTER_POSITION 2
#define LABEL_POSITION 2
#define INITIAL_CODE_ADDRESS 100

#define NUMBER_POSITION 2

#define NUMBERS_PREFIX ".data"
#define STRING_PREFIX ".string"
#define ENTRY_PREFIX ".entry"
#define EXTERNAL_PREFIX ".extern"

#define SOURCE_FILE_EXTENSION ".as"
#define OBJECT_FILE_EXTENSION ".ob"
#define ENTRIES_FILE_EXTENSION ".ent"
#define EXTERNAL_FILE_EXTENSION ".ext"
